name: whisper
services:
  whisper_all_mp4:
    container_name: whisper
    environment:
      - model=base
      - language=Chinese
    volumes:
      - /data:/data
    image: zhangyiming748/whisper_all_mp4:latest