name: whisper
services:
  whisper_all_mp4:
    container_name: whisper
    environment:
      - model=base
      - language=Chinese
    volumes:
      - /data:/data
      - /model:/model
    image: zhangyiming748/whisper_all_mp4:latest
    deploy:
      resources:
        limits:
          cpus: '7.3'
          memory: 7890M