name: whisper
services:
  whisper_all_mp4:
    container_name: whisper
    environment:
      - model=large-v3
      - language=Japanese
      - model_dir=/path/to/your/directory
    volumes:
      - /data:/data
    image: zhangyiming748/whisper_all_mp4:latest